version: '2'

services:
  taiga:
    build: .
    ports:
      - 80:80
      # - 443:443 # To enable SSL, uncomment this line. See "Enable SSL" below.
    depends_on:
      - postgres
      - events
      - rabbit 
      - redis

      # To enable taiga-events, uncomment the following lines:
      # - events
      # - rabbit
      # - redis
    restart: always
    environment:
      # Hostname for your instance of Taiga. Required.
      TAIGA_HOSTNAME: taiga.roost.com

      # Database variables. Required.
      TAIGA_DB_HOST: postgres
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password

      # Enable SSL internally, within the Docker container. Optional.
      # This is not great. I suggest using something on top of this
      # to enable SSL. See the example example-nginx-ssl.conf file
      # for an alternative way to enable SSL.
      # TAIGA_SSL: 'True'

      # Enable SSL externally, preferred method
      # TAIGA_SSL_BY_REVERSE_PROXY: 'True'
      # TAIGA_ENABLE_EMAIL: 'True'
      # TAIGA_EMAIL_FROM: 'daniel.eagy@gmail.com'
      # TAIGA_EMAIL_USE_TLS: 'True'
      # TAIGA_EMAIL_HOST: 'smtp.google.com'
      # TAIGA_EMAIL_PORT: 587
      # TAIGA_EMAIL_USER: 'daniel.eagy@gmail.com'
      # TAIGA_EMAIL_PASS: 'Ygae.DJE-1989'
    volumes:
      # Media and uploads directory. Required (or you will lose all uploads)
      - ./media:/usr/src/taiga-back/media

      # Taiga configuration directory. Makes it easier to change configuration.
      - ./taiga-conf:/taiga

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: taigadb
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: password
    ports:
      - 5432
    volumes:
      # Postgres data directory. This ensures the database is not lost.
      - ./pgdata:/var/lib/postgresql/data


  # To enable taiga-events, uncomment the following lines:
  rabbit:
    image: rabbitmq:3
    hostname: rabbit
  
  redis:
    image: redis:3
  
  celery:
    image: celery
    links:
      - rabbit
  
  events:
    image: benhutchins/taiga-events
    links:
      - rabbit
